name: macOS
on: [push, pull_request]
jobs:
  macOS-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, macos-11]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@main
      with:
        cvmfs_repositories: 'sft.cern.ch'
        run_local_checkout: 'true'
    - name: Test CernVM-FS
      run: |
       echo "### Dump default.local ###"
       cat /etc/cvmfs/default.local
       echo "### Try to ls on /Users/Shared/cvmfs/sft.cern.ch/ ###"
       ls /Users/Shared/cvmfs/sft.cern.ch/
