name: ubuntu
on:
  push:
  pull_request:
  schedule:
    - cron:  '44 4 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Test CernVM-FS
      run: |
        echo "### Dump default.local ###"
        cat /etc/cvmfs/default.local
        echo "### Test /cvmfs/lhcb.cern.ch ###"
        ls /cvmfs/lhcb.cern.ch
        echo "### Test /cvmfs/auger.egi.eu ###"
        ls /cvmfs/auger.egi.eu
        echo "### Test /cvmfs/dune.opensciencegrid.org ###"
        ls /cvmfs/dune.opensciencegrid.org
        echo "### Test /cvmfs/sw.hsf.org ###"
        ls /cvmfs/sw.hsf.org
        echo "### Test /cvmfs/sft.cern.ch ###"
        ls /cvmfs/sft.cern.ch
